apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/dyjo4949/argo-cd-kyverno
    targetRevision: main