apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kyverno
  source:
    repoURL: 'https://kyverno.github.io/kyverno/'
    chart: kyverno-policies
    targetRevision: 3.0.0
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true