apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kyverno
  project: default
  source:
    path: policies
    repoURL: https://github.com/dyjo4949/argo-cd-kyverno
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}